export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const NEXT_IMAGE = "NEXT_IMAGE";
export const PREV_IMAGE = "PREV_IMAGE";
export const CHANGE_ACTIVE_IMAGE = "CHANGE_ACTIVE_IMAGE";
